name: Docker Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        mode: [mcp, http]

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.${{ matrix.mode }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ matrix.mode }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.mode }}
